from __future__ import annotations

import logging

from app.baseline import evaluate_risk
from app.core.config import Settings
from app.core.constants import ENGINE_RULE_BASED_BASELINE
from app.core.exceptions import DomainValidationError
from app.schemas.lifestyle import (
    LegacyLifestyleRequest,
    LegacyLifestyleResponse,
    LifestyleRiskResponse,
    WellnessLifestyleRequest,
)

logger = logging.getLogger("entwin.ai.lifestyle")

_LEGACY_FACTOR_TO_CODE = {
    "fatigue": "LOW_SLEEP",
    "deshydratation": "LOW_HYDRATION",
    "sedentarite": "LOW_ACTIVITY",
    "surcharge": "HIGH_STRESS",
}

_LEGACY_RISK_TO_LEVEL = {
    "normal": "LOW",
    "fatigue": "MODERATE",
    "deshydratation": "MODERATE",
    "sedentarite": "MODERATE",
    "surcharge": "HIGH",
}


class LifestyleService:
    """Production lifestyle scoring is rule-based.

    `lifestyle_risk_model.joblib` is a DecisionTree trained on synthetic scores
    whose labels were generated by `evaluate_risk()` plus label noise. It is not
    used for API predictions.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings

    def predict_from_wellness(self, request: WellnessLifestyleRequest) -> LifestyleRiskResponse:
        domain_scores = self._wellness_to_scores(request)
        if not domain_scores:
            raise DomainValidationError("At least one lifestyle signal is required")

        factors = [
            code
            for code, score in domain_scores.items()
            if score < self._settings.lifestyle_score_threshold
        ]
        average = sum(domain_scores.values()) / len(domain_scores)
        if not factors:
            risk_level = "LOW"
        elif len(factors) == 1:
            risk_level = "MODERATE"
        else:
            risk_level = "HIGH"

        logger.info("prediction success model=lifestyle-baseline engine=%s", ENGINE_RULE_BASED_BASELINE)
        return LifestyleRiskResponse(
            risk_level=risk_level,
            score=round(average, 1),
            engine=ENGINE_RULE_BASED_BASELINE,
            factors=factors,
            model_version=None,
        )

    def predict_from_scores(self, request: LegacyLifestyleRequest) -> LegacyLifestyleResponse:
        raw = evaluate_risk(
            sleep_score=request.sleep_score,
            hydration_score=request.hydration_score,
            activity_score=request.activity_score,
            stress_score=request.stress_score,
        )
        factors = [_LEGACY_FACTOR_TO_CODE.get(name, name.upper()) for name in raw["contributing_factors"]]
        score = round(
            (
                request.sleep_score
                + request.hydration_score
                + request.activity_score
                + request.stress_score
            )
            / 4.0,
            1,
        )
        logger.info("prediction success model=lifestyle-baseline engine=%s", ENGINE_RULE_BASED_BASELINE)
        return LegacyLifestyleResponse(
            risk=raw["risk"],
            confidence=raw["confidence"],
            contributing_factors=raw["contributing_factors"],
            engine=ENGINE_RULE_BASED_BASELINE,
            risk_level=_LEGACY_RISK_TO_LEVEL.get(raw["risk"], "MODERATE"),
            score=score,
            factors=factors,
        )

    def _wellness_to_scores(self, request: WellnessLifestyleRequest) -> dict[str, float]:
        settings = self._settings
        scores: dict[str, float] = {}
        if request.average_sleep_minutes is not None:
            scores["LOW_SLEEP"] = _ratio_score(request.average_sleep_minutes, settings.sleep_target_minutes)
        if request.average_hydration_ml is not None:
            scores["LOW_HYDRATION"] = _ratio_score(request.average_hydration_ml, settings.hydration_target_ml)
        if request.weekly_workout_minutes is not None:
            scores["LOW_ACTIVITY"] = _ratio_score(
                request.weekly_workout_minutes, settings.workout_target_weekly_minutes
            )
        if request.average_daily_steps is not None:
            scores["LOW_STEPS"] = _ratio_score(request.average_daily_steps, settings.steps_target)
        if request.average_stress is not None:
            scores["HIGH_STRESS"] = _inverted_ten_scale(request.average_stress)
        if request.average_fatigue is not None:
            scores["HIGH_FATIGUE"] = _inverted_ten_scale(request.average_fatigue)
        if request.average_mood is not None:
            scores["LOW_MOOD"] = _direct_ten_scale(request.average_mood)
        return scores


def _ratio_score(value: float, target: float) -> float:
    if target <= 0:
        return 0.0
    return float(max(0.0, min(100.0, (value / target) * 100.0)))


def _inverted_ten_scale(level: float) -> float:
    return float(max(0.0, min(100.0, (10.0 - level) * 10.0)))


def _direct_ten_scale(level: float) -> float:
    return float(max(0.0, min(100.0, level * 10.0)))
