SLEEP_RISK_DISCLAIMER = (
    "This result is an informational lifestyle risk indicator and is not a medical diagnosis."
)

SLEEP_MODEL_NAME = "sleep-risk"
SLEEP_MODEL_VERSION = "1.0.0"
LIFESTYLE_MODEL_NAME = "lifestyle-risk"
LIFESTYLE_MODEL_VERSION = "1.0.0"

ENGINE_RULE_BASED_BASELINE = "RULE_BASED_BASELINE"
ENGINE_ML_MODEL = "ML_MODEL"
ENGINE_BASELINE_ESTIMATOR = "BASELINE_ESTIMATOR"
